### ISSUE TITLE
错误的css背景样式

### ISSUE THREAD

**Issue by cxgreat2014** [newpanjing/simpleui#354]
**bug描述**
* 在使用django-ckeditor时，发现后台各弹出面板背景存在问题，如图所示
* ![image](https://user-images.githubusercontent.com/15062548/112988640-a5efa500-9196-11eb-8502-2b66603b0e6c.png)

**重现步骤**
** repeat step **
1. 安装django-editor插件
2. models内使用ckeditor_uploader.fields.RichTextUploadingField, 并将该模型注册入admin
3. 在后台编辑对象，点击打开编辑器的图片上传面板，鼠标放上去

**错误原因**
** error reason**
`static/admin/simpleui-x/theme/green.css`第49-52行
https://github.com/newpanjing/simpleui/blob/master/simpleui/static/admin/simpleui-x/theme/green.css#L49-L52

**修复方法**
** repair method**

针对性修复方案：注入以下代码
```css
        .cke_reset_all tbody tr:hover td,
        .cke_reset_all tbody tr:hover th {
            background-color: white !important;
        }
```

通用修复方法：css加入类名选择
